repos:
  - repo: https://github.com/jonasbb/pre-commit-latex-hooks
    rev: v1.4.0
    hooks:
      - id: cleveref-capitalization
      - id: consistent-spelling
        args:
            [
              "--emph=et al.",
              "--emph=a priori",
              "--emph=a posteriori",
              "--emph=e.g.",
              "--emph=i.e.",
              '--regex=naive=\bna(i|\\"i)ve',
              "--emph=etc.",
              "--regex=hyperparameter=\bhyper-parameter",
              "--regex=hyperparameters=\bhyper-parameters",
              "--regex=dataset=\bdataset",
              "--regex=datasets=\bdata-sets",
              "main.tex",
              "thesis_main.tex"
            ]
      - id: csquotes
      - id: no-space-in-cite
      - id: tilde-cite
      - id: unique-labels
        files: ./main.tex
      - id: unique-labels
        files: ./thesis_main.tex
      - id: cleveref-instead-of-autoref
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: trailing-whitespace
        files: ".*\\.(?:py)$"
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: trailing-whitespace
        files: "main.tex"
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: trailing-whitespace
        files: "thesis_main.tex"
